;; -*- no-byte-compile: t; -*-

(package! ace-window)
(package! cape)
(package! citar)
(package! company)
(package! corfu)
(package! corfu-doc)
(package! ctrlf)
(package! deadgrep)
(package! dired-narrow)
(package! easy-kill)
(package! emacsql-sqlite-builtin)
(package! git-link)
(package! groovy-mode)
(package! kind-icon)
;; (package! ligma :recipe (:local-repo "lisp/ligma"))
(package! mathpix.el :recipe (:host github :repo "jethrokuan/mathpix.el"))
(package! modus-themes)
(package! multiple-cursors)
(package! org-present)
(package! org-roam :recipe (:host github :repo "org-roam/org-roam"))
(package! org-roam-bibtex)
(package! org-roam-ui)
(package! ox-hugo)
(package! ox-reveal)
(package! ox-texinfo+ :recipe (:host github :repo "tarsius/ox-texinfo-plus"))
(package! parinfer-rust-mode)
(package! redo)
(package! ripgrep)
(package! rustic)
(package! super-save)
(package! swiper)
(package! thrift)
(package! tree-sitter)
(package! tree-sitter-langs)
(package! try)
;;(package! drag-stuff)
